<?php

namespace KundanIn\ClickHouseLaravel\Database;

use Illuminate\Database\Query\Grammars\Grammar;

/**
 * ClickHouse query grammar for Laravel.
 *
 * Compiles Laravel query builder instances into ClickHouse-compatible SQL.
 * Handles ClickHouse-specific syntax such as SAMPLE, FINAL, PREWHERE,
 * ALTER TABLE UPDATE/DELETE, and ClickHouse date/array functions.
 */
class ClickHouseQueryGrammar extends Grammar
{
    /**
     * Compile a select query into SQL.
     *
     * Injects ClickHouse-specific clauses (FINAL, SAMPLE, PREWHERE)
     * into the SQL generated by the parent compiler.
     *
     * @param  \Illuminate\Database\Query\Builder  $query
     * @return string
     */
    public function compileSelect($query): string
    {
        $sql = parent::compileSelect($query);

        if (! $query instanceof ClickHouseQueryBuilder) {
            return $sql;
        }

        // Inject FINAL after the table name in FROM clause
        if ($query->final) {
            $table = $this->wrapTable($query->from);
            $sql = str_replace("from {$table}", "from {$table} FINAL", $sql);
        }

        // Inject SAMPLE after FROM (and after FINAL if present)
        if ($query->sample !== null) {
            $table = $this->wrapTable($query->from);
            $target = $query->final ? "from {$table} FINAL" : "from {$table}";
            $sql = str_replace($target, "{$target} SAMPLE {$query->sample}", $sql);
        }

        // Inject PREWHERE before WHERE
        if (! empty($query->prewhere)) {
            $prewhere = $this->compilePrewhere($query);
            if ($prewhere) {
                $wherePos = stripos($sql, ' where ');
                if ($wherePos !== false) {
                    $sql = substr($sql, 0, $wherePos).' '.$prewhere.substr($sql, $wherePos);
                } else {
                    $sql .= ' '.$prewhere;
                }
            }
        }

        return $sql;
    }

    /**
     * Compile the PREWHERE conditions into SQL.
     *
     * @param  \KundanIn\ClickHouseLaravel\Database\ClickHouseQueryBuilder  $query
     * @return string
     */
    protected function compilePrewhere(ClickHouseQueryBuilder $query): string
    {
        $conditions = [];

        foreach ($query->prewhere as $i => $where) {
            $column = $this->wrap($where['column']);
            $value = $this->parameter($where['value']);
            $condition = "{$column} {$where['operator']} {$value}";

            if ($i > 0) {
                $condition = $where['boolean'].' '.$condition;
            }

            $conditions[] = $condition;
        }

        return 'PREWHERE '.implode(' ', $conditions);
    }

    /**
     * Wrap a table in keyword identifiers, prepending the database name.
     *
     * @param  mixed  $table
     * @param  string|null  $prefix
     * @return string
     */
    public function wrapTable($table, $prefix = null): string
    {
        if ($table instanceof \Illuminate\Database\Query\Expression) {
            return $table->getValue($this);
        }

        if (is_string($table) && str_contains($table, '.')) {
            return parent::wrapTable($table, $prefix);
        }

        if (is_string($table) && $this->connection) {
            $database = $this->connection->getDatabaseName();
            if ($database) {
                return parent::wrapTable($database.'.'.$table, $prefix);
            }
        }

        return parent::wrapTable($table, $prefix);
    }

    /**
     * Compile a LIMIT clause.
     *
     * @param  \Illuminate\Database\Query\Builder  $query
     * @param  int  $limit
     * @return string
     */
    public function compileLimit($query, $limit): string
    {
        return 'LIMIT '.(int) $limit;
    }

    /**
     * Compile an INSERT statement for ClickHouse.
     *
     * @param  \Illuminate\Database\Query\Builder  $query
     * @param  array  $values
     * @return string
     */
    public function compileInsert($query, array $values): string
    {
        if (empty($values)) {
            return '';
        }

        $table = $this->wrapTable($query->from);
        $columns = implode(', ', array_map([$this, 'wrap'], array_keys($values[0])));
        $placeholders = implode(', ', array_map(function ($row) {
            return '('.implode(', ', array_map([$this, 'parameter'], $row)).')';
        }, $values));

        return "INSERT INTO {$table} ({$columns}) VALUES {$placeholders}";
    }

    /**
     * Compile an UPDATE statement using ALTER TABLE syntax.
     *
     * ClickHouse does not support traditional UPDATE queries. Instead,
     * updates are performed via ALTER TABLE ... UPDATE ... WHERE.
     *
     * @param  \Illuminate\Database\Query\Builder  $query
     * @param  array  $values
     * @return string
     *
     * @throws \Exception
     */
    public function compileUpdate($query, array $values): string
    {
        $table = $this->wrapTable($query->from);
        $where = $this->compileClickHouseWheres($query);

        if (empty($where)) {
            throw new \Exception('UPDATE queries on ClickHouse require a WHERE clause for safety.');
        }

        $sets = [];
        foreach ($values as $column => $value) {
            $sets[] = $this->wrap($column).' = '.$this->quoteClickHouseValue($value);
        }

        return "ALTER TABLE {$table} UPDATE ".implode(', ', $sets)." {$where}";
    }

    /**
     * Compile a DELETE statement using ALTER TABLE syntax.
     *
     * ClickHouse does not support traditional DELETE queries. Instead,
     * deletes are performed via ALTER TABLE ... DELETE WHERE.
     *
     * @param  \Illuminate\Database\Query\Builder  $query
     * @return string
     *
     * @throws \Exception
     */
    public function compileDelete($query): string
    {
        $table = $this->wrapTable($query->from);
        $where = $this->compileClickHouseWheres($query);

        if (empty($where)) {
            throw new \Exception('DELETE queries on ClickHouse require a WHERE clause for safety.');
        }

        return "ALTER TABLE {$table} DELETE {$where}";
    }

    /**
     * Compile a TRUNCATE TABLE statement.
     *
     * @param  \Illuminate\Database\Query\Builder  $query
     * @return array
     */
    public function compileTruncate($query): array
    {
        return ['TRUNCATE TABLE '.$this->wrapTable($query->from) => []];
    }

    // ---------------------------------------------------------------
    // WHERE type methods — dispatched automatically by parent Grammar
    // ---------------------------------------------------------------

    /**
     * Compile a "where date" clause using ClickHouse's toDate() function.
     *
     * @param  \Illuminate\Database\Query\Builder  $query
     * @param  array  $where
     * @return string
     */
    protected function whereDate($query, $where)
    {
        return 'toDate('.$this->wrap($where['column']).") {$where['operator']} ".$this->parameter($where['value']);
    }

    /**
     * Compile a "where time" clause using ClickHouse's formatDateTime().
     *
     * @param  \Illuminate\Database\Query\Builder  $query
     * @param  array  $where
     * @return string
     */
    protected function whereTime($query, $where)
    {
        return 'formatDateTime('.$this->wrap($where['column']).", '%H:%i:%S') {$where['operator']} ".$this->parameter($where['value']);
    }

    /**
     * Compile a "where day" clause using ClickHouse's toDayOfMonth() function.
     *
     * @param  \Illuminate\Database\Query\Builder  $query
     * @param  array  $where
     * @return string
     */
    protected function whereDay($query, $where)
    {
        return 'toDayOfMonth('.$this->wrap($where['column']).") {$where['operator']} ".$this->parameter($where['value']);
    }

    /**
     * Compile a "where month" clause using ClickHouse's toMonth() function.
     *
     * @param  \Illuminate\Database\Query\Builder  $query
     * @param  array  $where
     * @return string
     */
    protected function whereMonth($query, $where)
    {
        return 'toMonth('.$this->wrap($where['column']).") {$where['operator']} ".$this->parameter($where['value']);
    }

    /**
     * Compile a "where year" clause using ClickHouse's toYear() function.
     *
     * @param  \Illuminate\Database\Query\Builder  $query
     * @param  array  $where
     * @return string
     */
    protected function whereYear($query, $where)
    {
        return 'toYear('.$this->wrap($where['column']).") {$where['operator']} ".$this->parameter($where['value']);
    }

    /**
     * Compile a "where array has" clause using ClickHouse's has() function.
     *
     * @param  \Illuminate\Database\Query\Builder  $query
     * @param  array  $where
     * @return string
     */
    protected function whereArrayHas($query, $where)
    {
        return 'has('.$this->wrap($where['column']).', '.$this->parameter($where['value']).')';
    }

    /**
     * Compile a "where not array has" clause.
     *
     * @param  \Illuminate\Database\Query\Builder  $query
     * @param  array  $where
     * @return string
     */
    protected function whereNotArrayHas($query, $where)
    {
        return 'NOT has('.$this->wrap($where['column']).', '.$this->parameter($where['value']).')';
    }

    /**
     * Compile a "where array has any" clause using ClickHouse's hasAny() function.
     *
     * @param  \Illuminate\Database\Query\Builder  $query
     * @param  array  $where
     * @return string
     */
    protected function whereArrayHasAny($query, $where)
    {
        $params = implode(', ', array_map([$this, 'parameter'], $where['values']));

        return 'hasAny('.$this->wrap($where['column']).', ['.$params.'])';
    }

    /**
     * Compile a "where not array has any" clause.
     *
     * @param  \Illuminate\Database\Query\Builder  $query
     * @param  array  $where
     * @return string
     */
    protected function whereNotArrayHasAny($query, $where)
    {
        $params = implode(', ', array_map([$this, 'parameter'], $where['values']));

        return 'NOT hasAny('.$this->wrap($where['column']).', ['.$params.'])';
    }

    /**
     * Compile a "where array has all" clause using ClickHouse's hasAll() function.
     *
     * @param  \Illuminate\Database\Query\Builder  $query
     * @param  array  $where
     * @return string
     */
    protected function whereArrayHasAll($query, $where)
    {
        $params = implode(', ', array_map([$this, 'parameter'], $where['values']));

        return 'hasAll('.$this->wrap($where['column']).', ['.$params.'])';
    }

    /**
     * Compile a "where not array has all" clause.
     *
     * @param  \Illuminate\Database\Query\Builder  $query
     * @param  array  $where
     * @return string
     */
    protected function whereNotArrayHasAll($query, $where)
    {
        $params = implode(', ', array_map([$this, 'parameter'], $where['values']));

        return 'NOT hasAll('.$this->wrap($where['column']).', ['.$params.'])';
    }

    // ---------------------------------------------------------------
    // ALTER TABLE where compilation (values embedded, no placeholders)
    // ---------------------------------------------------------------

    /**
     * Compile WHERE clauses for ALTER TABLE statements.
     *
     * ALTER TABLE UPDATE/DELETE in ClickHouse does not support parameter
     * placeholders, so values must be embedded directly in the SQL.
     *
     * @param  \Illuminate\Database\Query\Builder  $query
     * @return string
     */
    protected function compileClickHouseWheres($query): string
    {
        if (empty($query->wheres)) {
            return '';
        }

        $wheres = [];

        foreach ($query->wheres as $where) {
            $method = 'whereClickHouse'.$where['type'];
            if (method_exists($this, $method)) {
                $wheres[] = $this->{$method}($query, $where);
            } else {
                $wheres[] = $this->whereClickHouseBasic($query, $where);
            }
        }

        if (count($wheres) > 1) {
            return 'WHERE '.implode(' '.strtolower($query->wheres[0]['boolean'] ?? 'and').' ', $wheres);
        }

        return count($wheres) > 0 ? 'WHERE '.$wheres[0] : '';
    }

    /**
     * Compile a basic WHERE clause for ALTER TABLE statements.
     *
     * @param  \Illuminate\Database\Query\Builder  $query
     * @param  array  $where
     * @return string
     */
    protected function whereClickHouseBasic($query, array $where): string
    {
        return $this->wrap($where['column'])." {$where['operator']} ".$this->quoteClickHouseValue($where['value']);
    }

    /**
     * Compile a date WHERE clause for ALTER TABLE statements.
     *
     * @param  \Illuminate\Database\Query\Builder  $query
     * @param  array  $where
     * @return string
     */
    protected function whereClickHouseDate($query, array $where): string
    {
        return 'toDate('.$this->wrap($where['column']).") {$where['operator']} ".$this->quoteClickHouseValue($where['value']);
    }

    /**
     * Quote a value for direct embedding in ClickHouse SQL.
     *
     * Used for ALTER TABLE statements that do not support parameter binding.
     *
     * @param  mixed  $value
     * @return string
     */
    protected function quoteClickHouseValue($value): string
    {
        if (is_null($value)) {
            return 'NULL';
        }

        if (is_bool($value)) {
            return $value ? '1' : '0';
        }

        if (is_numeric($value)) {
            return (string) $value;
        }

        $value = (string) $value;
        $escaped = str_replace(
            ['\\', "'", '"', "\n", "\r", "\t", "\0", "\x1a"],
            ['\\\\', "\\'", '\\"', '\\n', '\\r', '\\t', '\\0', '\\Z'],
            $value
        );

        return "'".$escaped."'";
    }
}
